name: GitHub Actions Demo
on:
  push: 
    branches: ["main"]
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches: ["main"]
  
  schedule:
    - cron:  '15 6 * * sun'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo "event name is:" ${{ github.event_name }}
      - name: List all files in the repo
          run | 
            ls-la
            
################################################################################################################################     
                                                     # VUSI ANSWER #
################################################################################################################################
            
# on:
#   push:
#     branches: [ main ]
#     paths-ignore: [.github/**]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     - cron: '15 6 * * 0'
#   workflow_dispatch:            
#   jobs:
#   Build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "🎉 The job was triggered by event: ${{ github.event_name }}"
#           echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
        
#       - uses: actions/checkout@v3.0.2

#       - name: List files in the repository
#         run: |
#           echo "The repository ${{ github.repository }} contains the following files:"
#           tree
